version: "3.9"

services:
  nextjs:
    build:
      context: ./e-commerce
      dockerfile: Dockerfile
    container_name: e-commerce
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
      - whisper

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    container_name: whisper_api
    expose:
      - "5000"
    environment:
      - WHISPER_MODEL=base

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  caddy:
    image: caddy:2
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nextjs
      - whisper

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
