FROM node:18-alpine

WORKDIR /app

# Install dependencies (cached)
COPY package*.json ./
RUN npm install

# Copy rest of the code
COPY . .

# Expose Next.js dev port
EXPOSE 3000

# Run Next.js in development mode
CMD ["npm", "run", "dev"]
